### ISSUE TITLE
Custom feature vectors

### ISSUE THREAD

**Issue by maroth** [UNIFR-PR-Group/Pattern-Recognition#2]
The program is very slow. By using custom feature vectors, we could improve the performance drastically. Ideas are:

-Only use pixels that are not 0 in most training set elements
-Use the mean value for each row of pixels
-Use a lower resolution

I suggest implementing these custom features as methods on the dataPoint object that transform the existing feature vector to the new feature vector.

**Comment by Borreguin** [comment]
Using a new feature vector of 28x2 size.... doing the test.
